### ISSUE TITLE
Compilation error due to missing dependency

### ISSUE THREAD

**Issue by eluzgin** [Tandemly/eos-api-service#14]
yarn install v1.3.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 📃  Building fresh packages...
[1/2] ⠐ fsevents: http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz
[-/2] ⠐ waiting...
[-/2] ⠐ waiting...
[-/2] ⠐ waiting...
warning Error running install script for optional dependency: "/Users/z002mnr/Blockchain/EOS/express-rest-es2017-boilerplate/node_modules/fsevents: Command failed.\nExit code: 1\nCommand: node install\nArguments: \nDirectory: /Users/z002mnr/Blockchain/EOS/express-rest-es2017-boilerplate/node_modules/fsevents\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.38\nnode-pre-gyp info using node@9.3.0 | darwin | x64\nnode-pre-gyp info check checked for \"/Users/z002mnr/Blockchain/EOS/express-rest-es2017-boilerplate/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node\" (not found)\nnode-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz\nnode-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz\nnode-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@9.3.0 (node-v59 ABI) (falling back to source compile with node-gyp) \nnode-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/z002mnr/Blockchain/EOS/express-rest-es2017-boilerplate/node_modules/node-pre-gyp/lib/util/compile.js:77:29)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)\nnode-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:389:16)\nnode-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:152:19)\nnode-pre-gyp ERR! System Darwin 16.7.0\nnode-pre-gyp ERR! command \"/usr/local/Cellar/node/9.3.0_1/bin/node\" \"/Users/z002mnr/Blockchain/EOS/express-rest-es2017-boilerplate/node_modules/fsevents/node_modules/.bin/✨  Done in 6.02s.
a0999b14c845:express-rest-es2017-boilerplate z002mnr$ wget https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz
--2018-01-31 16:59:25--  https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz
Resolving fsevents-binaries.s3-us-west-2.amazonaws.com... 52.218.192.193
Connecting to fsevents-binaries.s3-us-west-2.amazonaws.com|52.218.192.193|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-31 16:59:25 ERROR 404: Not Found.

If you load listing in browser: 
https://fsevents-binaries.s3-us-west-2.amazonaws.com/ 

You will see that file fse-v1.1.2-node-v59-darwin-x64.tar.gz doesn't exists.
The closest key that exists: v1.1.2/fse-v1.1.2-node-v57-darwin-x64.tar.gz

**Comment by eluzgin** [comment]
Ok I figured out  solution: update fsevents library from v1.1.2 to v1.1.3
